// apps/desktop/frontend/src/components/NavRail.tsx
import { type MouseEvent } from 'react'
import {
  CircleEllipsis,
  CircleHelp,
  FileText,
  GitBranch,
  Home,
  MessageCircle,
  RefreshCcw,
  Settings,
  SlidersHorizontal,
  type LucideIcon,
} from 'lucide-react'
import { NavBarLink } from 'react-windows-ui'
import type { NavItem } from '../types'

interface NavRailProps {
  topNav: NavItem[]
  bottomNav: NavItem[]
  currentPage: string
  onChange: (page: string) => void
}

const icons: Record<string, LucideIcon> = {
  home: Home,
  settings: SlidersHorizontal,
  flow: GitBranch,
  refresh: RefreshCcw,
  document: CircleHelp,
  chat: MessageCircle,
  sliders: Settings,
  grid: CircleEllipsis,
}

function NavRail({ topNav, bottomNav, currentPage, onChange }: NavRailProps) {
  return (
    <aside className="side-nav">
      <nav className="side-nav-list">
        <ul className="side-nav-section">
          {topNav.map((item) => (
            <NavButton key={item.id} item={item} active={currentPage === item.id} onClick={() => onChange(item.id)} />
          ))}
        </ul>
        <ul className="side-nav-section">
          {bottomNav.map((item) => (
            <NavButton key={item.id} item={item} active={currentPage === item.id} onClick={() => onChange(item.id)} />
          ))}
        </ul>
      </nav>
    </aside>
  )
}

function NavButton({ item, active, onClick }: { item: NavItem, active: boolean, onClick: () => void }) {
  const Icon = icons[item.icon] ?? FileText
  return (
    <NavBarLink
      href="#"
      text={item.label}
      icon={<Icon size={21} strokeWidth={2} />}
      active={active}
      showBadge={item.badge}
      onClick={(event: MouseEvent<HTMLAnchorElement>) => {
        event.preventDefault()
        onClick()
      }}
    />
  )
}

export default NavRail

// go/desktopui/frontend/src/components/NavRail.vue
<script setup lang="ts">
import {
  CircleEllipsis,
  CircleHelp,
  FileText,
  GitBranch,
  Home,
  MessageCircle,
  RefreshCcw,
  Settings,
  SlidersHorizontal,
} from '@lucide/vue'
import type { Component } from 'vue'
import type { NavItem } from '../types'

defineProps<{
  appTitle: string
  appVersion: string
  topNav: NavItem[]
  bottomNav: NavItem[]
  currentPage: string
}>()

const emit = defineEmits<{
  change: [page: string]
}>()

const icons: Record<string, Component> = {
  home: Home,
  settings: SlidersHorizontal,
  flow: GitBranch,
  refresh: RefreshCcw,
  document: CircleHelp,
  chat: MessageCircle,
  sliders: Settings,
  grid: CircleEllipsis,
}

function iconFor(item: NavItem): Component {
  return icons[item.icon] ?? FileText
}
</script>

<template>
  <aside class="side-nav">
    <nav class="flex flex-1 flex-col justify-between px-1.5 py-1.5">
      <div class="space-y-0.5">
        <button
          v-for="item in topNav"
          :key="item.id"
          class="side-nav-item"
          :class="{ 'side-nav-active': currentPage === item.id }"
          @click="emit('change', item.id)"
        >
          <component :is="iconFor(item)" class="side-nav-icon" :stroke-width="2" />
          <span class="side-nav-label">{{ item.label }}</span>
          <span v-if="item.badge" class="absolute right-0.5 top-0.5 rounded-full bg-amber-400 px-1.5 py-0.5 text-[10px] text-white">
            {{ item.badge }}
          </span>
        </button>
      </div>

      <div class="space-y-0.5">
        <button
          v-for="item in bottomNav"
          :key="item.id"
          class="side-nav-item"
          :class="{ 'side-nav-active': currentPage === item.id }"
          @click="emit('change', item.id)"
        >
          <component :is="iconFor(item)" class="side-nav-icon" :stroke-width="2" />
          <span class="side-nav-label">{{ item.label }}</span>
        </button>
      </div>
    </nav>
  </aside>
</template>
