// apps/desktop/frontend/src/components/WindowControls.tsx
import { useEffect, useState } from 'react'
import { Minus, Square, X } from 'lucide-react'
import { Window } from '@wailsio/runtime'

function WindowControls() {
  const [maximised, setMaximised] = useState(false)

  async function syncMaximised() {
    try {
      setMaximised(await Window.IsMaximised())
    } catch {
      setMaximised(false)
    }
  }

  async function toggleMaximise() {
    try {
      if (await Window.IsMaximised()) {
        await Window.Restore()
      } else {
        await Window.Maximise()
      }
      await syncMaximised()
    } catch {
      return
    }
  }

  async function minimise() {
    try {
      await Window.Minimise()
    } catch {
      return
    }
  }

  async function close() {
    try {
      await Window.Close()
    } catch {
      return
    }
  }

  useEffect(() => {
    void syncMaximised()
  }, [])

  return (
    <div className="window-controls no-drag">
      <button className="window-button" title="最小化" type="button" onClick={minimise}>
        <Minus size={15} />
      </button>
      <button className="window-button" title={maximised ? '还原' : '最大化'} type="button" onClick={toggleMaximise}>
        <Square size={13} />
      </button>
      <button className="window-button window-button-close" title="关闭" type="button" onClick={close}>
        <X size={16} />
      </button>
    </div>
  )
}

export default WindowControls

// go/desktopui/frontend/src/components/WindowControls.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Minus, Square, X } from '@lucide/vue'
import { Window } from '@wailsio/runtime'

const maximised = ref(false)

async function syncMaximised() {
  try {
    maximised.value = await Window.IsMaximised()
  } catch {
    maximised.value = false
  }
}

async function toggleMaximise() {
  try {
    if (await Window.IsMaximised()) {
      await Window.Restore()
    } else {
      await Window.Maximise()
    }
    await syncMaximised()
  } catch {
    return
  }
}

async function minimise() {
  try {
    await Window.Minimise()
  } catch {
    return
  }
}

async function close() {
  try {
    await Window.Close()
  } catch {
    return
  }
}

void syncMaximised()
</script>

<template>
  <div class="flex h-11 items-center">
    <button class="titlebar-button" title="最小化" @click="minimise">
      <Minus :size="15" />
    </button>
    <button class="titlebar-button" :title="maximised ? '还原' : '最大化'" @click="toggleMaximise">
      <Square :size="13" />
    </button>
    <button class="titlebar-button hover:bg-red-500 hover:text-white" title="关闭" @click="close">
      <X :size="16" />
    </button>
  </div>
</template>
