// apps/desktop/frontend/src/pages/RuntimeView.vue
<script setup lang="ts">
import SettingField from '../components/SettingField.vue'
import type { SettingsGroup } from '../types'

defineProps<{
  groups: SettingsGroup[]
}>()

const emit = defineEmits<{
  fieldChange: [id: string, value: string | boolean]
}>()
</script>

<template>
  <section class="min-h-0 flex-1 overflow-y-auto p-3">
    <div class="mx-auto max-w-4xl space-y-3">
      <div v-for="group in groups" :key="group.title" class="panel overflow-hidden">
        <div class="section-title">{{ group.title }}</div>
        <div class="px-3">
          <SettingField
            v-for="field in group.fields"
            :key="field.id"
            :field="field"
            @change="(id, value) => emit('fieldChange', id, value)"
          />
        </div>
      </div>
    </div>
  </section>
</template>

// apps/desktop/frontend/src/pages/RuntimeView.tsx
import SettingField from '../components/SettingField'
import type { SettingsGroup } from '../types'

interface RuntimeViewProps {
  groups: SettingsGroup[]
  onFieldChange: (id: string, value: string | boolean) => void
}

function RuntimeView({ groups, onFieldChange }: RuntimeViewProps) {
  return (
    <section className="page scroll-page">
      <div className="content-stack">
        {groups.map((group) => (
          <section className="surface settings-panel" key={group.title}>
            <div className="section-heading">
              <h2>{group.title}</h2>
            </div>
            {group.fields.map((field) => (
              <SettingField key={field.id} field={field} onChange={onFieldChange} />
            ))}
          </section>
        ))}
      </div>
    </section>
  )
}

export default RuntimeView
