// go/desktopui/frontend/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { AlertCircle } from '@lucide/vue'
import { Dialogs } from '@wailsio/runtime'
import NavRail from './components/NavRail.vue'
import WindowControls from './components/WindowControls.vue'
import DashboardView from './pages/DashboardView.vue'
import InfoView from './pages/InfoView.vue'
import LogsView from './pages/LogsView.vue'
import RuntimeView from './pages/RuntimeView.vue'
import StrategyView from './pages/StrategyView.vue'
import {
  buildDefaultConfig,
  loadAppModel,
  loadRuntimeConfig,
  previewReverseFill,
  runRuntimeConfig,
  saveRuntimeConfig,
  saveSettings,
} from './services/shell'
import { applyConfigToShell, updateAppSettingsField, updateRuntimeConfigField, type AppModel } from './services/stateMapper'
import type { RuntimeConfig, ShellState } from './types'

const shell = ref<ShellState | null>(null)
const model = ref<AppModel | null>(null)
const currentPage = ref('dashboard')
const loading = ref(true)
const busy = ref(false)
const error = ref('')
const notice = ref('')

const config = computed(() => model.value?.config ?? null)

onMounted(async () => {
  try {
    const loaded = await loadAppModel()
    model.value = loaded
    shell.value = loaded.shell
    currentPage.value = loaded.shell.currentPage || 'dashboard'
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err)
  } finally {
    loading.value = false
  }
})

function setConfig(next: RuntimeConfig) {
  if (!model.value || !shell.value) {
    return
  }
  model.value.config = next
  shell.value = applyConfigToShell(shell.value, model.value.settings, model.value.config, model.value.reverseFillPreview)
}

function setNotice(message: string) {
  notice.value = message
}

async function withBusy(action: () => Promise<void>) {
  busy.value = true
  error.value = ''
  try {
    await action()
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err)
  } finally {
    busy.value = false
  }
}

function updateConfigField(id: string, value: string | boolean) {
  if (!config.value) {
    return
  }
  setConfig(updateRuntimeConfigField(config.value, id, value))
}

function updateSettingsField(id: string, value: string | boolean) {
  if (!model.value || !shell.value) {
    return
  }
  model.value.settings = updateAppSettingsField(model.value.settings, id, value)
  shell.value = applyConfigToShell(shell.value, model.value.settings, model.value.config, model.value.reverseFillPreview)
}

function updateURL(value: string) {
  if (!config.value) {
    return
  }
  setConfig({ ...config.value, url: value })
}

async function autoConfig() {
  await withBusy(async () => {
    if (!config.value?.url) {
      throw new Error('问卷链接不能为空')
    }
    const next = await buildDefaultConfig(config.value.url)
    setConfig({
      ...config.value,
      ...next,
      target: config.value.target,
      threads: config.value.threads,
      random_ip_enabled: config.value.random_ip_enabled,
      proxy_source: config.value.proxy_source,
    })
    setNotice('问卷配置已生成')
  })
}

async function loadConfigFromDialog() {
  await withBusy(async () => {
    const path = await Dialogs.OpenFile({
      Title: '载入配置',
      CanChooseFiles: true,
      Filters: [{ DisplayName: 'JSON 配置', Pattern: '*.json' }],
    })
    if (!path || Array.isArray(path)) {
      return
    }
    const loaded = await loadRuntimeConfig(path)
    if (model.value) {
      model.value.configPath = loaded.path
    }
    setConfig(loaded.config)
    setNotice('配置已载入')
  })
}

async function saveConfigToDialog() {
  await withBusy(async () => {
    if (!config.value) {
      return
    }
    const path = await Dialogs.SaveFile({
      Title: '保存配置',
      Filename: `${config.value.survey_title || 'wjx_config'}.json`,
      Filters: [{ DisplayName: 'JSON 配置', Pattern: '*.json' }],
    })
    if (!path) {
      return
    }
    const saved = await saveRuntimeConfig(config.value, path)
    if (model.value) {
      model.value.configPath = saved.path
    }
    setConfig(saved.config)
    setNotice('配置已保存')
  })
}

async function chooseReverseFillFile() {
  await withBusy(async () => {
    const path = await Dialogs.OpenFile({
      Title: '选择反填 Excel',
      CanChooseFiles: true,
      Filters: [{ DisplayName: 'Excel 文件', Pattern: '*.xlsx;*.xlsm' }],
    })
    if (!path || Array.isArray(path) || !config.value) {
      return
    }
    setConfig({ ...config.value, reverse_fill_enabled: true, reverse_fill_source_path: path })
  })
}

async function previewReverseFillFile() {
  await withBusy(async () => {
    if (!config.value) {
      return
    }
    const preview = await previewReverseFill(config.value)
    if (!model.value || !shell.value) {
      return
    }
    model.value.reverseFillPreview = preview
    shell.value = applyConfigToShell(shell.value, model.value.settings, model.value.config, preview)
    setNotice(`已预览 ${preview.total_data_rows} 行`)
  })
}

async function saveAppSettings() {
  await withBusy(async () => {
    if (!model.value || !shell.value) {
      return
    }
    model.value.settings = await saveSettings(model.value.settings)
    shell.value = applyConfigToShell(shell.value, model.value.settings, model.value.config, model.value.reverseFillPreview)
    setNotice('设置已保存')
  })
}

async function runSurvey() {
  await withBusy(async () => {
    if (!config.value) {
      return
    }
    const state = await runRuntimeConfig(config.value)
    if (!shell.value) {
      return
    }
    shell.value = {
      ...shell.value,
      dashboard: {
        ...shell.value.dashboard,
        progressCurrent: state.result?.success ?? 0,
        progressPercent: state.result && shell.value.dashboard.progressTarget > 0
          ? Math.round((state.result.success / shell.value.dashboard.progressTarget) * 100)
          : shell.value.dashboard.progressPercent,
        statusText: state.result ? `成功 ${state.result.success}，失败 ${state.result.fail}` : '运行结束',
      },
      logLines: [
        ...(state.events ?? []).map((event) => `[${event.worker || 'core'}] ${event.message}`),
        ...shell.value.logLines,
      ].slice(0, 200),
    }
    setNotice('任务已返回结果')
  })
}
</script>

<template>
  <div class="h-screen overflow-hidden bg-[#f4f8fc] text-neutral-950 dark:bg-slate-950 dark:text-slate-100">
    <div v-if="loading" class="grid h-full place-items-center text-sm text-neutral-500">载入中</div>

    <div v-else-if="error && !shell" class="grid h-full place-items-center">
      <div class="panel flex max-w-md items-start gap-3 p-5 text-sm">
        <AlertCircle class="mt-0.5 text-red-500" :size="18" />
        <div>
          <div class="font-medium text-neutral-950 dark:text-slate-50">服务连接失败</div>
          <div class="mt-1 text-neutral-500 dark:text-slate-400">{{ error }}</div>
        </div>
      </div>
    </div>

    <div v-else-if="shell" class="flex h-full flex-col">
      <header class="app-titlebar drag-region">
        <div class="flex min-w-0 items-center gap-3">
          <div class="app-logo">
            SC
          </div>
          <div class="flex min-w-0 items-baseline gap-1.5">
            <span class="app-title truncate">{{ shell.appTitle }} v4.0.6</span>
            <span class="app-build">(84563)</span>
          </div>
          <span class="app-badge">最新</span>
        </div>
        <WindowControls />
      </header>

      <div class="flex min-h-0 flex-1">
        <NavRail
          :app-title="shell.appTitle"
          :app-version="shell.appVersion"
          :top-nav="shell.topNav"
          :bottom-nav="shell.bottomNav"
          :current-page="currentPage"
          @change="currentPage = $event"
        />

        <main class="flex min-w-0 flex-1 flex-col">
          <div v-if="error" class="mx-3 mt-2 rounded-md border border-red-100 bg-red-50 px-3 py-1.5 text-xs text-red-700 dark:border-red-950 dark:bg-red-950 dark:text-red-200">
            {{ error }}
          </div>
          <div v-if="notice" class="mx-3 mt-2 rounded-md border border-blue-100 bg-blue-50 px-3 py-1.5 text-xs text-blue-700 dark:border-blue-950 dark:bg-blue-950 dark:text-blue-200">
            {{ notice }}
          </div>
          <DashboardView
            v-if="currentPage === 'dashboard'"
            :dashboard="shell.dashboard"
            :logs="shell.logLines"
            :busy="busy"
            @update-url="updateURL"
            @auto-config="autoConfig"
            @load-config="loadConfigFromDialog"
            @save-config="saveConfigToDialog"
            @open-runtime="currentPage = 'runtime'"
            @target-change="updateConfigField('target', String($event))"
            @threads-change="updateConfigField('threads', String($event))"
            @random-ip-change="updateConfigField('random-ip', $event)"
            @proxy-source-change="updateConfigField('proxy-source', $event)"
            @run="runSurvey"
          />
          <RuntimeView v-else-if="currentPage === 'runtime'" :groups="shell.runtimeGroups" @field-change="updateConfigField" />
          <StrategyView v-else-if="currentPage === 'strategy'" :rules="shell.strategyRules" :dimensions="shell.dimensionGroups" />
          <InfoView
            v-else-if="currentPage === 'reverse-fill'"
            title="反填"
            :reverse-fill="shell.reverseFillPlan"
            :reverse-fill-path="config?.reverse_fill_source_path"
            :busy="busy"
            @choose-reverse-fill="chooseReverseFillFile"
            @preview-reverse-fill="previewReverseFillFile"
          />
          <LogsView v-else-if="currentPage === 'logs'" :logs="shell.logLines" />
          <InfoView v-else-if="currentPage === 'community'" title="社区" :items="shell.communityItems" />
          <InfoView
            v-else-if="currentPage === 'settings'"
            title="设置"
            :settings="shell.settingsGroups"
            :busy="busy"
            @setting-change="updateSettingsField"
            @save-settings="saveAppSettings"
          />
          <InfoView v-else title="更多" :metrics="[...shell.aboutItems, ...shell.donateItems, ...shell.ipUsageItems]" />
        </main>
      </div>
    </div>
  </div>
</template>

// apps/desktop/frontend/src/App.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AlertCircle } from 'lucide-react'
import { AppTheme, LoaderBusy } from 'react-windows-ui'
import { Dialogs } from '@wailsio/runtime'
import NavRail from './components/NavRail'
import WindowControls from './components/WindowControls'
import DashboardView from './pages/DashboardView'
import InfoView from './pages/InfoView'
import LogsView from './pages/LogsView'
import RuntimeView from './pages/RuntimeView'
import StrategyView from './pages/StrategyView'
import {
  buildDefaultConfig,
  cancelRuntimeConfig,
  loadAppModel,
  loadProxyStatus,
  loadRunTaskState,
  loadRuntimeConfig,
  previewReverseFill,
  saveRuntimeConfig,
  saveSettings,
  startRuntimeConfig,
} from './services/shell'
import {
  applyConfigToShell,
  updateAppSettingsField,
  updateRuntimeConfigField,
  type AppModel,
} from './services/stateMapper'
import type { ProxyStatus, RunTaskState, RuntimeConfig, ShellState } from './types'

function App() {
  const [model, setModel] = useState<AppModel | null>(null)
  const [currentPage, setCurrentPage] = useState('dashboard')
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [runState, setRunState] = useState<RunTaskState | null>(null)
  const [proxyStatus, setProxyStatus] = useState<ProxyStatus | null>(null)
  const [runtimeLogLines, setRuntimeLogLines] = useState<string[]>([])
  const previousPage = useRef(currentPage)
  const runPollTimer = useRef<number | null>(null)

  const config = model?.config ?? null
  const runBusy = busy || Boolean(runState?.running || runState?.canceling)

  const shell = useMemo<ShellState | null>(() => {
    if (!model) {
      return null
    }
    const mapped = applyConfigToShell(
      model.shell,
      model.settings,
      model.config,
      model.reverseFillPreview,
      runState,
      proxyStatus,
    )
    return {
      ...mapped,
      logLines: [...runtimeLogLines, ...mapped.logLines].slice(0, 200),
    }
  }, [model, proxyStatus, runState, runtimeLogLines])

  const stopRunPolling = useCallback(() => {
    if (!runPollTimer.current) {
      return
    }
    window.clearInterval(runPollTimer.current)
    runPollTimer.current = null
  }, [])

  const pollRunState = useCallback(async () => {
    try {
      const [nextRun, nextProxy] = await Promise.all([loadRunTaskState(), loadProxyStatus()])
      setRunState(nextRun)
      setProxyStatus(nextProxy)
      if (!nextRun.running && !nextRun.canceling) {
        stopRunPolling()
        if (nextRun.events?.length) {
          setRuntimeLogLines((lines) => [
            ...nextRun.events!.map((event) => `[${event.worker || 'core'}] ${event.message}`),
            ...lines,
          ].slice(0, 200))
        }
      }
    } catch (err) {
      stopRunPolling()
      setError(err instanceof Error ? err.message : String(err))
    }
  }, [stopRunPolling])

  const startRunPolling = useCallback(() => {
    if (runPollTimer.current) {
      return
    }
    runPollTimer.current = window.setInterval(() => {
      void pollRunState()
    }, 500)
    void pollRunState()
  }, [pollRunState])

  useEffect(() => {
    let ignore = false
    async function load() {
      try {
        const loaded = await loadAppModel()
        if (ignore) {
          return
        }
        setModel(loaded)
        setCurrentPage(loaded.shell.currentPage || 'dashboard')
        const [proxy, run] = await Promise.allSettled([loadProxyStatus(), loadRunTaskState()])
        if (ignore) {
          return
        }
        if (proxy.status === 'fulfilled') {
          setProxyStatus(proxy.value)
        }
        if (run.status === 'fulfilled') {
          setRunState(run.value)
          if (run.value.running) {
            startRunPolling()
          }
        }
      } catch (err) {
        if (!ignore) {
          setError(err instanceof Error ? err.message : String(err))
        }
      } finally {
        if (!ignore) {
          setLoading(false)
        }
      }
    }
    void load()
    return () => {
      ignore = true
      stopRunPolling()
    }
  }, [startRunPolling, stopRunPolling])

  async function withBusy(action: () => Promise<void>) {
    setBusy(true)
    setError('')
    try {
      await action()
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    } finally {
      setBusy(false)
    }
  }

  function setConfig(next: RuntimeConfig) {
    setModel((current) => current ? { ...current, config: next } : current)
  }

  function updateConfigField(id: string, value: string | boolean) {
    if (!config) {
      return
    }
    setConfig(updateRuntimeConfigField(config, id, value))
  }

  function updateSettingsField(id: string, value: string | boolean) {
    setModel((current) => current
      ? { ...current, settings: updateAppSettingsField(current.settings, id, value) }
      : current)
  }

  function updateURL(value: string) {
    if (!config) {
      return
    }
    setConfig({ ...config, url: value })
  }

  async function autoConfig() {
    await withBusy(async () => {
      if (!config?.url) {
        throw new Error('问卷链接不能为空')
      }
      const next = await buildDefaultConfig(config.url)
      setConfig({
        ...config,
        ...next,
        target: config.target,
        threads: config.threads,
        random_ip_enabled: config.random_ip_enabled,
        proxy_source: config.proxy_source,
      })
      setNotice('问卷配置已生成')
    })
  }

  async function loadConfigFromDialog() {
    await withBusy(async () => {
      const path = await Dialogs.OpenFile({
        Title: '载入配置',
        CanChooseFiles: true,
        Filters: [{ DisplayName: 'JSON 配置', Pattern: '*.json' }],
      })
      if (!path || Array.isArray(path)) {
        return
      }
      const loaded = await loadRuntimeConfig(path)
      setModel((current) => current
        ? { ...current, configPath: loaded.path, config: loaded.config }
        : current)
      setNotice('配置已载入')
    })
  }

  async function saveConfigToDialog() {
    await withBusy(async () => {
      if (!config) {
        return
      }
      const path = await Dialogs.SaveFile({
        Title: '保存配置',
        Filename: `${config.survey_title || 'wjx_config'}.json`,
        Filters: [{ DisplayName: 'JSON 配置', Pattern: '*.json' }],
      })
      if (!path) {
        return
      }
      const saved = await saveRuntimeConfig(config, path)
      setModel((current) => current
        ? { ...current, configPath: saved.path, config: saved.config }
        : current)
      setNotice('配置已保存')
    })
  }

  async function chooseReverseFillFile() {
    await withBusy(async () => {
      const path = await Dialogs.OpenFile({
        Title: '选择反填 Excel',
        CanChooseFiles: true,
        Filters: [{ DisplayName: 'Excel 文件', Pattern: '*.xlsx;*.xlsm' }],
      })
      if (!path || Array.isArray(path) || !config) {
        return
      }
      setConfig({ ...config, reverse_fill_enabled: true, reverse_fill_source_path: path })
    })
  }

  async function previewReverseFillFile() {
    await withBusy(async () => {
      if (!config) {
        return
      }
      const preview = await previewReverseFill(config)
      setModel((current) => current ? { ...current, reverseFillPreview: preview } : current)
      setNotice(`已预览 ${preview.total_data_rows} 行`)
    })
  }

  async function saveAppSettings() {
    await withBusy(async () => {
      if (!model) {
        return
      }
      const saved = await saveSettings(model.settings)
      setModel((current) => current ? { ...current, settings: saved } : current)
      setNotice('设置已保存')
    })
  }

  async function runSurvey() {
    await withBusy(async () => {
      if (!config) {
        return
      }
      setRuntimeLogLines([])
      const nextRun = await startRuntimeConfig(config)
      const nextProxy = await loadProxyStatus()
      setRunState(nextRun)
      setProxyStatus(nextProxy)
      startRunPolling()
      setNotice('任务已启动')
    })
  }

  async function cancelRun() {
    await withBusy(async () => {
      const nextRun = await cancelRuntimeConfig()
      const nextProxy = await loadProxyStatus()
      setRunState(nextRun)
      setProxyStatus(nextProxy)
      startRunPolling()
      setNotice('正在停止任务')
    })
  }

  const scheme = shell?.themeMode === 'dark' || shell?.themeMode === 'light' ? shell.themeMode : 'system'
  const pageMotion = previousPage.current === currentPage ? 'page-motion-initial' : 'page-motion-forward'

  useEffect(() => {
    previousPage.current = currentPage
  }, [currentPage])

  if (loading) {
    return (
      <div className="boot-screen">
        <LoaderBusy isLoading />
      </div>
    )
  }

  if (error && !shell) {
    return (
      <div className="boot-screen">
        <div className="error-panel">
          <AlertCircle size={18} />
          <div>
            <strong>服务连接失败</strong>
            <span>{error}</span>
          </div>
        </div>
      </div>
    )
  }

  if (!shell) {
    return null
  }

  return (
    <div className="app-root">
      <AppTheme scheme={scheme} color="#0067c0" colorDarkMode="#60cdff" />
      <header className="app-titlebar drag-region">
        <div className="brand-block">
          <img className="app-logo" src="/appicon.png" alt="" draggable={false} />
          <div className="brand-text">
            <span>{shell.appTitle}</span>
            <small>{shell.appVersion}</small>
          </div>
        </div>
        <WindowControls />
      </header>

      <div className="app-frame">
        <NavRail
          topNav={shell.topNav}
          bottomNav={shell.bottomNav}
          currentPage={currentPage}
          onChange={setCurrentPage}
        />

        <main className="workspace">
          <div className="message-stack">
            {error ? <div className="status-banner status-banner-danger">{error}</div> : null}
            {notice ? <div className="status-banner status-banner-info">{notice}</div> : null}
          </div>

          <div key={currentPage} className={`page-transition ${pageMotion}`}>
            {currentPage === 'dashboard' ? (
              <DashboardView
                dashboard={shell.dashboard}
                logs={shell.logLines}
                busy={runBusy}
                onUpdateUrl={updateURL}
                onAutoConfig={autoConfig}
                onLoadConfig={loadConfigFromDialog}
                onSaveConfig={saveConfigToDialog}
                onOpenRuntime={() => setCurrentPage('runtime')}
                onTargetChange={(value) => updateConfigField('target', String(value))}
                onThreadsChange={(value) => updateConfigField('threads', String(value))}
                onRandomIpChange={(value) => updateConfigField('random-ip', value)}
                onProxySourceChange={(value) => updateConfigField('proxy-source', value)}
                onRun={runSurvey}
                onCancelRun={cancelRun}
              />
            ) : null}
            {currentPage === 'runtime' ? (
              <RuntimeView groups={shell.runtimeGroups} onFieldChange={updateConfigField} />
            ) : null}
            {currentPage === 'strategy' ? (
              <StrategyView rules={shell.strategyRules} dimensions={shell.dimensionGroups} />
            ) : null}
            {currentPage === 'reverse-fill' ? (
              <InfoView
                title="反填"
                reverseFill={shell.reverseFillPlan}
                reverseFillPath={config?.reverse_fill_source_path}
                busy={busy}
                onChooseReverseFill={chooseReverseFillFile}
                onPreviewReverseFill={previewReverseFillFile}
              />
            ) : null}
            {currentPage === 'logs' ? <LogsView logs={shell.logLines} /> : null}
            {currentPage === 'community' ? <InfoView title="社区" items={shell.communityItems} /> : null}
            {currentPage === 'settings' ? (
              <InfoView
                title="设置"
                settings={shell.settingsGroups}
                busy={busy}
                onSettingChange={updateSettingsField}
                onSaveSettings={saveAppSettings}
              />
            ) : null}
            {currentPage === 'more' ? (
              <InfoView title="更多" metrics={[...shell.aboutItems, ...shell.donateItems, ...shell.ipUsageItems]} />
            ) : null}
          </div>
        </main>
      </div>
    </div>
  )
}

export default App
